version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./users.sql:/docker-entrypoint-initdb.d/users.sql:ro
    ports:
      - "5432:5432"
volumes:
  db_data:
